name: Deploy to CloudPanel

on:
  push:
    branches: [ "githubaction" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar secrets
        run: |
          echo "Verificando variables:"
          echo "Host: 200.58.121.145"
          echo "Port: 5931"
          echo "Username: armydevs-cutman"
          echo "Password: ${{ secrets.VPS_PASSWORD && '***** (configurado)' || 'NO CONFIGURADO' }}"

      - name: Despliegue por SSH con contraseña
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: "200.58.121.145"
          port: "5931"
          username: "armydevs-cutman"
          password: ${{ secrets.VPS_PASSWORD }}
          use_insecure_cipher: true
          cipher: aes128-cbc
          timeout: 60s
          command_timeout: 10m
          envs: GITHUB_REPOSITORY=${{ github.repository }}
          debug: true
          script: |
            cd /home/armydevs-cutman/htdocs
            
            # Clonar o actualizar el repo
            if [ ! -d "cutman" ]; then
              git clone https://github.com/${{ github.repository }}.git cutman
            fi

            cd cutman
            git fetch origin
            git checkout githubaction
            git pull origin githubaction

            # Instalar dependencias y build
            npm install
            npm run build

            # Mover archivos build a directorio público
            rm -rf /home/armydevs-cutman/htdocs/cutman/public
            cp -r dist /home/armydevs-cutman/htdocs/cutman/public

            # Health check básico
            if [ -f "/home/armydevs-cutman/htdocs/cutman/public/index.html" ]; then
              echo "✔️ Despliegue exitoso"
            else
              echo "❌ Error en el despliegue"
              exit 1
            fi
