name: Deploy to CloudPanel

on:
  push:
    branches: [ "githubaction" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue por SSH con contraseña
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/htdocs
            
            # Clonar o actualizar el repo
            if [ ! -d "cutman" ]; then
              git clone https://github.com/${{ github.repository }}.git cutman
            fi

            cd cutman
            git fetch origin
            git checkout githubaction
            git pull origin githubaction

            # Instalar dependencias y build
            npm install
            npm run build

            # Mover archivos build a directorio público
            rm -rf /home/${{ secrets.VPS_USER }}/htdocs/cutman/public
            cp -r dist /home/${{ secrets.VPS_USER }}/htdocs/cutman/public

            # Health check básico
            if [ -f "/home/${{ secrets.VPS_USER }}/htdocs/cutman/public/index.html" ]; then
              echo "✔️ Despliegue exitoso"
            else
              echo "❌ Error en el despliegue"
              exit 1
            fi
